FROM golang:1.5.3
RUN go get github.com/tools/godep
ENV DOCKER_VERSION 1.9

RUN curl -sL https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VERSION} > /usr/local/bin/docker && \
    chmod +x /usr/local/bin/docker

WORKDIR /go/src/github.com/ehazlett/interlock

COPY . /go/src/github.com/ehazlett/interlock
