FROM golang:1.3-cross
ADD . /go/src/github.com/ehazlett/interlock
ADD https://get.docker.com/builds/Linux/x86_64/docker-1.5.0 /usr/local/bin/docker
RUN chmod +x /usr/local/bin/docker
WORKDIR /go/src/github.com/ehazlett/interlock

