version: '3'

networks:
  overlay_net:

services:

 interlock:
    image: ehazlett/interlock:mytag
    command: -D run -c /etc/interlock/config.toml
    tty: true
    networks:
      - overlay_net
    deploy:
      replicas: 1
      placement:
        constraints:
          [ node.role == manager ]
    volumes:
        - ${PWD}/docs/examples/nginx-swarm-stack-machine/config.toml:/etc/interlock/config.toml:ro
        - ${PWD}/docs/examples/nginx-swarm-stack-machine/nginx-template.conf:/nginx-template.conf:ro
        - ${DOCKER_CERT_PATH}:/var/lib/boot2docker:ro


 nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    networks:
      - overlay_net
    deploy:
      replicas: 1
      placement:
        constraints:
          [ node.role == manager ]
    ports:
        - 80:80
        - 7070:7070
    labels:
        - "interlock.ext.name=nginx"

 app:
    image: ehazlett/docker-demo:latest
    networks:
      - overlay_net
    deploy:
      replicas: 2
      placement:
        constraints:
          [ node.role != manager ]
    ports:
        - 8080:8080
    labels:
        - "interlock.hostname="
        - "interlock.domain=_"
        - "interlock.context_root=/web"
        - "interlock.port=8080"
        - "interlock.network=mystack_overlay_net"
