#!/bin/bash
docker build -t interlock-build -f Dockerfile.build .
docker run -ti --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/go/src/github.com/ehazlett/interlock -w /go/src/github.com/ehazlett/interlock/interlock interlock-build make build image
